MODE_CONSOLE_TYPE = 1
MODE_SERVICE_TYPE = 2

HEARTBEAT_SLEEPING = 5  # seconds
HEARTBEAT_INTERVAL = 60 # seconds

DEFAULT_DATA_INTERVAL   = 60 * 60 # seconds
DEFAULT_DATA_OVERLAP    =  3 * 60 # seconds
DEFAULT_TICKER_INTERVAL = "1h"

EXECUTION_STATUS_RUNNING = 'running'
EXECUTION_STATUS_SUCCESS = 'success'
EXECUTION_STATUS_FAILED  = 'failed'

SECRET_DATABASE_CREDENTIALS = "project_database_credentials"